name: Ping Supabase
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        env:
          URL: ${{ https://ppjlkdgqrwsyuhcxuahw.supabase.co }}
          KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "URL is: $URL"
          curl -v "${URL}/rest/v1/" \
            -H "apikey: ${KEY}" \
            -H "Authorization: Bearer ${KEY}"
