name: Ping Supabase
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl "https://ppjlkdgqrwsyuhcxuahw.supabase.co/rest/v1/" -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"
